import datetime
x = datetime.datetime(2024,2,20)
x = x.strftime("%A")
print(x)
x = datetime.datetime(2024,2,21)
x = x.strftime("%A")
print(x)
x = datetime.datetime(2024,2,22)
x= x.strftime("%A")
print(x)